name: Slither

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  analyze-optimism-dai-bridge:
    name: Slither for optimism-dai-bridge
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/optimism-dai-bridge
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        with:
          node-version: 16
  analyze-arbitrum-dai-bridge:
    name: Slither for arbitrum-dai-bridge
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/arbitrum-dai-bridge
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        with:
          node-version: 16
