name: Slither

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  analyze-optimism-dai-bridge:
    name: Slither for optimism-dai-bridge
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        with:
          node-version: 16
          target: ./packages/optimism-dai-bridge
  analyze-arbitrum-dai-bridge:
    name: Slither for arbitrum-dai-bridge
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        with:
          node-version: 16
          target: ./packages/arbitrum-dai-bridge
